import { GameCatalog } from '@/types';

export const GAMES_CATALOG: GameCatalog[] = [
  // ==================== INSTALLED GAMES ====================

  // FPS / Battle Royale
  { id: 'csgo', name: 'Counter-Strike 2', coverImage: '/games/cs2.jpg', bannerImage: '/games/cs2-banner.jpg', genre: 'FPS', players: 'Multiplayer', rating: 9.2, description: 'Tactical team-based FPS', supportsStats: true, statsApi: 'steam', defaultExePath: 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\Counter-Strike Global Offensive\\game\\bin\\win64\\cs2.exe' },
  { id: 'valorant', name: 'Valorant', coverImage: '/games/valorant.jpg', bannerImage: '/games/valorant-banner.jpg', genre: 'FPS', players: 'Multiplayer', rating: 8.8, description: 'Tactical 5v5 shooter', supportsStats: true, statsApi: 'valorant', defaultExePath: 'C:\\Riot Games\\VALORANT\\live\\VALORANT.exe' },
  { id: 'fortnite', name: 'Fortnite', coverImage: '/games/fortnite.jpg', bannerImage: '/games/fortnite-banner.jpg', genre: 'Battle Royale', players: 'Multiplayer', rating: 8.5, description: 'Build and battle royale', supportsStats: true, statsApi: 'fortnite', defaultExePath: 'C:\\Program Files\\Epic Games\\Fortnite\\FortniteGame\\Binaries\\Win64\\FortniteClient-Win64-Shipping.exe' },
  { id: 'overwatch2', name: 'Overwatch 2', coverImage: '/games/overwatch.jpg', bannerImage: '/games/overwatch-banner.jpg', genre: 'FPS', players: 'Multiplayer', rating: 7.8, description: 'Team-based hero shooter', supportsStats: false, statsApi: 'manual', defaultExePath: 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\Overwatch\\Overwatch.exe' },
  { id: 'css', name: 'Counter-Strike Source v34', coverImage: '/games/css.jpg', bannerImage: '/games/css-banner.jpg', genre: 'FPS', players: 'Multiplayer', rating: 8.5, description: 'Classic tactical shooter', supportsStats: false, statsApi: 'none', defaultExePath: 'D:\\New folder\\Counter Strike Source v34\\play-css-v34.exe' },
  { id: 'rust', name: 'Rust', coverImage: '/games/rust.jpg', bannerImage: '/games/rust-banner.jpg', genre: 'Survival', players: 'Multiplayer', rating: 8.2, description: 'Harsh survival multiplayer', supportsStats: false, statsApi: 'steam', defaultExePath: 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\Rust\\RustClient.exe' },

  // MOBA
  { id: 'lol', name: 'League of Legends', coverImage: '/games/lol.jpg', bannerImage: '/games/lol-banner.jpg', genre: 'MOBA', players: 'Multiplayer', rating: 8.5, description: 'The definitive MOBA', supportsStats: false, statsApi: 'manual', defaultExePath: 'C:\\Riot Games\\League of Legends\\LeagueClient.exe' },
  { id: 'dota2', name: 'Dota 2', coverImage: '/games/dota2.jpg', bannerImage: '/games/dota2-banner.jpg', genre: 'MOBA', players: 'Multiplayer', rating: 8.3, description: 'Complex competitive MOBA', supportsStats: false, statsApi: 'manual', defaultExePath: 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\dota 2 beta\\game\\bin\\win64\\dota2.exe' },

  // Open World / Action
  { id: 'fivem', name: 'FiveM (GTA V RP)', coverImage: '/games/fivem.jpg', bannerImage: '/games/fivem-banner.jpg', genre: 'Open World', players: 'Multiplayer', rating: 8.8, description: 'GTA V roleplay multiplayer', supportsStats: false, statsApi: 'none', defaultExePath: 'C:\\Users\\%USERNAME%\\AppData\\Local\\FiveM\\FiveM.exe' },
  { id: 'hogwarts', name: 'Hogwarts Legacy', coverImage: '/games/hogwarts.jpg', bannerImage: '/games/hogwarts-banner.jpg', genre: 'RPG', players: 'Single Player', rating: 8.3, description: 'Wizarding world adventure', supportsStats: false, statsApi: 'none', defaultExePath: 'C:\\Program Files\\Epic Games\\HogwartsLegacy\\HogwartsLegacy.exe' },

  // Racing / Sports
  { id: 'rocketleague', name: 'Rocket League', coverImage: '/games/rocketleague.jpg', bannerImage: '/games/rocketleague-banner.jpg', genre: 'Sports', players: 'Multiplayer', rating: 8.7, description: 'Soccer with cars', supportsStats: false, statsApi: 'manual', defaultExePath: 'C:\\Program Files\\Epic Games\\rocketleague\\Binaries\\Win64\\RocketLeague.exe' },
  { id: 'asphalt', name: 'Asphalt Legends Unite', coverImage: '/games/asphalt.jpg', bannerImage: '/games/asphalt-banner.jpg', genre: 'Racing', players: 'Multiplayer', rating: 7.5, description: 'Arcade street racing', supportsStats: false, statsApi: 'none', defaultExePath: 'C:\\Program Files\\Epic Games\\AsphaltLegendsUnite\\Asphalt9_epic_x64_rtl.exe' },

  // Party / Co-op
  { id: 'fallguys', name: 'Fall Guys', coverImage: '/games/fallguys.jpg', bannerImage: '/games/fallguys-banner.jpg', genre: 'Party', players: 'Multiplayer', rating: 7.5, description: 'Battle royale party game', supportsStats: false, statsApi: 'none', defaultExePath: 'C:\\Program Files\\Epic Games\\FallGuys\\FallGuys_client.exe' },
  { id: 'roblox', name: 'Roblox', coverImage: '/games/roblox.jpg', bannerImage: '/games/roblox-banner.jpg', genre: 'Platform', players: 'Multiplayer', rating: 7.5, description: 'User-created games platform', supportsStats: false, statsApi: 'none', defaultExePath: 'C:\\Users\\%USERNAME%\\AppData\\Local\\Roblox\\RobloxPlayerLauncher.exe' },
  { id: 'minecraft', name: 'Minecraft (TLauncher)', coverImage: '/games/minecraft.jpg', bannerImage: '/games/minecraft-banner.jpg', genre: 'Sandbox', players: 'Single/Multi', rating: 9.0, description: 'Block building sandbox', supportsStats: false, statsApi: 'none', defaultExePath: 'C:\\Users\\%USERNAME%\\AppData\\Roaming\\.minecraft\\TLauncher.exe' },

  // Strategy
  { id: 'generals', name: 'C&C Generals', coverImage: '/games/generals.jpg', bannerImage: '/games/generals-banner.jpg', genre: 'Strategy', players: 'Single/Multi', rating: 8.5, description: 'Classic RTS warfare', supportsStats: false, statsApi: 'none', defaultExePath: 'C:\\Program Files (x86)\\R.G. Mechanics\\Command and Conquer - Generals\\Command and Conquer Generals\\Generals.exe' },
  { id: 'zerohour', name: 'C&C Generals: Zero Hour', coverImage: '/games/zerohour.jpg', bannerImage: '/games/zerohour-banner.jpg', genre: 'Strategy', players: 'Single/Multi', rating: 8.7, description: 'Ultimate RTS expansion', supportsStats: false, statsApi: 'none', defaultExePath: 'C:\\Program Files (x86)\\R.G. Mechanics\\Command and Conquer - Generals\\Command and Conquer Generals Zero Hour\\Generals.exe' },

  // Mobile (via emulator)
  { id: 'freefire', name: 'Free Fire MAX', coverImage: '/games/freefire.jpg', bannerImage: '/games/freefire-banner.jpg', genre: 'Battle Royale', players: 'Multiplayer', rating: 7.0, description: 'Mobile battle royale', supportsStats: false, statsApi: 'none', defaultExePath: 'C:\\Program Files\\BlueStacks_nxt\\HD-Player.exe' },


  // ==================== APPS & TOOLS ====================
  { id: 'chrome', name: 'Google Chrome', coverImage: '/games/chrome.png', genre: 'App', players: 'Browser', rating: 9.0, description: 'Web browser', supportsStats: false, statsApi: 'none', defaultExePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe' },
  { id: 'discord', name: 'Discord', coverImage: '/games/discord.jpg', genre: 'App', players: 'Communication', rating: 8.5, description: 'Voice & text chat', supportsStats: false, statsApi: 'none', defaultExePath: 'C:\\Users\\%USERNAME%\\AppData\\Local\\Discord\\Update.exe --processStart Discord.exe' },
  { id: 'steam', name: 'Steam', coverImage: '/games/steam.jpg', genre: 'App', players: 'Launcher', rating: 9.0, description: 'Game store & launcher', supportsStats: false, statsApi: 'none', defaultExePath: 'C:\\Program Files (x86)\\Steam\\steam.exe' },
  { id: 'faceit', name: 'FACEIT', coverImage: '/games/faceit.jpg', genre: 'App', players: 'Competitive', rating: 8.0, description: 'Competitive gaming platform', supportsStats: false, statsApi: 'none', defaultExePath: 'C:\\Users\\%USERNAME%\\AppData\\Local\\FACEIT\\FACEIT.exe' },
  { id: 'medal', name: 'Medal.tv', coverImage: '/games/medal.jpg', genre: 'App', players: 'Recording', rating: 7.8, description: 'Game clip recorder', supportsStats: false, statsApi: 'none', defaultExePath: 'C:\\Users\\%USERNAME%\\AppData\\Local\\Medal\\Medal.exe' },
  { id: 'battlenet', name: 'Battle.net', coverImage: '/games/battlenet.jpg', genre: 'App', players: 'Launcher', rating: 7.5, description: 'Blizzard game launcher', supportsStats: false, statsApi: 'none', defaultExePath: 'C:\\Program Files (x86)\\Battle.net\\Battle.net Launcher.exe' },

  // ==================== NOT INSTALLED (available in catalog) ====================
  { id: 'apex', name: 'Apex Legends', coverImage: '/games/apex.jpg', bannerImage: '/games/apex-banner.jpg', genre: 'Battle Royale', players: 'Multiplayer', rating: 8.7, description: 'Hero-based battle royale', supportsStats: true, statsApi: 'apex', defaultExePath: '' },
  { id: 'pubg', name: 'PUBG: Battlegrounds', coverImage: '/games/pubg.jpg', bannerImage: '/games/pubg-banner.jpg', genre: 'Battle Royale', players: 'Multiplayer', rating: 8.0, description: 'Military battle royale', supportsStats: true, statsApi: 'pubg', defaultExePath: '' },
  { id: 'warzone', name: 'Call of Duty: Warzone', coverImage: '/games/warzone.jpg', bannerImage: '/games/warzone-banner.jpg', genre: 'Battle Royale', players: 'Multiplayer', rating: 8.3, description: 'Massive warfare battle royale', supportsStats: false, statsApi: 'manual', defaultExePath: '' },
  { id: 'r6siege', name: 'Rainbow Six Siege', coverImage: '/games/r6siege.jpg', bannerImage: '/games/r6siege-banner.jpg', genre: 'FPS', players: 'Multiplayer', rating: 8.6, description: 'Tactical destruction-based FPS', supportsStats: true, statsApi: 'r6', defaultExePath: '' },
  { id: 'thefinals', name: 'The Finals', coverImage: '/games/thefinals.jpg', bannerImage: '/games/thefinals-banner.jpg', genre: 'FPS', players: 'Multiplayer', rating: 8.0, description: 'Destructible arena shooter', supportsStats: false, statsApi: 'manual', defaultExePath: '' },
  { id: 'bo6', name: 'Call of Duty: BO6', coverImage: '/games/bo6.jpg', bannerImage: '/games/bo6-banner.jpg', genre: 'FPS', players: 'Multiplayer', rating: 8.5, description: 'Classic COD multiplayer', supportsStats: false, statsApi: 'manual', defaultExePath: '' },
  { id: 'deadlock', name: 'Deadlock', coverImage: '/games/deadlock.jpg', bannerImage: '/games/deadlock-banner.jpg', genre: 'MOBA Shooter', players: 'Multiplayer', rating: 8.4, description: 'Valve\'s hero shooter MOBA', supportsStats: false, statsApi: 'manual', defaultExePath: '' },
  { id: 'marvelrivals', name: 'Marvel Rivals', coverImage: '/games/marvelrivals.jpg', bannerImage: '/games/marvelrivals-banner.jpg', genre: 'FPS', players: 'Multiplayer', rating: 7.9, description: 'Marvel hero team shooter', supportsStats: false, statsApi: 'manual', defaultExePath: '' },
  { id: 'gtav', name: 'Grand Theft Auto V', coverImage: '/games/gtav.jpg', bannerImage: '/games/gtav-banner.jpg', genre: 'Open World', players: 'Single/Multi', rating: 9.5, description: 'Crime empire sandbox', supportsStats: false, statsApi: 'manual', defaultExePath: '' },
  { id: 'rdr2', name: 'Red Dead Redemption 2', coverImage: '/games/rdr2.jpg', bannerImage: '/games/rdr2-banner.jpg', genre: 'Open World', players: 'Single/Multi', rating: 9.7, description: 'Wild west masterpiece', supportsStats: false, statsApi: 'none', defaultExePath: '' },
  { id: 'cyberpunk', name: 'Cyberpunk 2077', coverImage: '/games/cyberpunk.jpg', bannerImage: '/games/cyberpunk-banner.jpg', genre: 'RPG', players: 'Single Player', rating: 8.5, description: 'Futuristic open world RPG', supportsStats: false, statsApi: 'none', defaultExePath: '' },
  { id: 'eldenring', name: 'Elden Ring', coverImage: '/games/eldenring.jpg', bannerImage: '/games/eldenring-banner.jpg', genre: 'Action RPG', players: 'Single/Multi', rating: 9.5, description: 'FromSoftware\'s magnum opus', supportsStats: false, statsApi: 'none', defaultExePath: '' },
  { id: 'bg3', name: 'Baldur\'s Gate 3', coverImage: '/games/bg3.jpg', bannerImage: '/games/bg3-banner.jpg', genre: 'RPG', players: 'Single/Co-op', rating: 9.6, description: 'Epic D&D RPG', supportsStats: false, statsApi: 'none', defaultExePath: '' },
  { id: 'diablo4', name: 'Diablo IV', coverImage: '/games/diablo4.jpg', bannerImage: '/games/diablo4-banner.jpg', genre: 'Action RPG', players: 'Multiplayer', rating: 7.8, description: 'Dark action RPG', supportsStats: false, statsApi: 'none', defaultExePath: '' },
  { id: 'destiny2', name: 'Destiny 2', coverImage: '/games/destiny2.jpg', bannerImage: '/games/destiny2-banner.jpg', genre: 'Looter Shooter', players: 'Multiplayer', rating: 8.0, description: 'Sci-fi looter shooter', supportsStats: false, statsApi: 'manual', defaultExePath: '' },
  { id: 'palworld', name: 'Palworld', coverImage: '/games/palworld.jpg', bannerImage: '/games/palworld-banner.jpg', genre: 'Survival', players: 'Multiplayer', rating: 7.5, description: 'Creature collecting survival', supportsStats: false, statsApi: 'none', defaultExePath: '' },
  { id: 'forza5', name: 'Forza Horizon 5', coverImage: '/games/forza5.jpg', bannerImage: '/games/forza5-banner.jpg', genre: 'Racing', players: 'Single/Multi', rating: 9.0, description: 'Open world racing', supportsStats: false, statsApi: 'none', defaultExePath: '' },
  { id: 'fifa25', name: 'EA FC 25', coverImage: '/games/fifa25.jpg', bannerImage: '/games/fifa25-banner.jpg', genre: 'Sports', players: 'Multiplayer', rating: 7.5, description: 'The beautiful game', supportsStats: false, statsApi: 'manual', defaultExePath: '' },
  { id: 'nba2k25', name: 'NBA 2K25', coverImage: '/games/nba2k25.jpg', bannerImage: '/games/nba2k25-banner.jpg', genre: 'Sports', players: 'Multiplayer', rating: 7.3, description: 'Basketball simulation', supportsStats: false, statsApi: 'none', defaultExePath: '' },
  { id: 'madden25', name: 'Madden NFL 25', coverImage: '/games/madden25.jpg', bannerImage: '/games/madden25-banner.jpg', genre: 'Sports', players: 'Multiplayer', rating: 6.5, description: 'American football sim', supportsStats: false, statsApi: 'none', defaultExePath: '' },
  { id: 'sf6', name: 'Street Fighter 6', coverImage: '/games/sf6.jpg', bannerImage: '/games/sf6-banner.jpg', genre: 'Fighting', players: 'Multiplayer', rating: 8.8, description: 'Iconic fighting game', supportsStats: false, statsApi: 'manual', defaultExePath: '' },
  { id: 'tekken8', name: 'Tekken 8', coverImage: '/games/tekken8.jpg', bannerImage: '/games/tekken8-banner.jpg', genre: 'Fighting', players: 'Multiplayer', rating: 8.6, description: 'King of iron fist', supportsStats: false, statsApi: 'manual', defaultExePath: '' },
  { id: 'mk1', name: 'Mortal Kombat 1', coverImage: '/games/mk1.jpg', bannerImage: '/games/mk1-banner.jpg', genre: 'Fighting', players: 'Multiplayer', rating: 8.0, description: 'Brutal fighting game', supportsStats: false, statsApi: 'manual', defaultExePath: '' },
  { id: 'genshin', name: 'Genshin Impact', coverImage: '/games/genshin.jpg', bannerImage: '/games/genshin-banner.jpg', genre: 'Action RPG', players: 'Single/Co-op', rating: 8.2, description: 'Anime open world RPG', supportsStats: false, statsApi: 'none', defaultExePath: '' },
  { id: 'wutheringwaves', name: 'Wuthering Waves', coverImage: '/games/wutheringwaves.jpg', bannerImage: '/games/wutheringwaves-banner.jpg', genre: 'Action RPG', players: 'Single Player', rating: 7.8, description: 'Anime action RPG', supportsStats: false, statsApi: 'none', defaultExePath: '' },
  { id: 'amongus', name: 'Among Us', coverImage: '/games/amongus.jpg', bannerImage: '/games/amongus-banner.jpg', genre: 'Party', players: 'Multiplayer', rating: 7.0, description: 'Social deduction game', supportsStats: false, statsApi: 'none', defaultExePath: '' },
  { id: 'ittakestwo', name: 'It Takes Two', coverImage: '/games/ittakestwo.jpg', bannerImage: '/games/ittakestwo-banner.jpg', genre: 'Co-op', players: 'Co-op', rating: 9.0, description: 'Award-winning co-op adventure', supportsStats: false, statsApi: 'none', defaultExePath: '' },
  { id: 'awayout', name: 'A Way Out', coverImage: '/games/awayout.jpg', bannerImage: '/games/awayout-banner.jpg', genre: 'Co-op', players: 'Co-op', rating: 7.8, description: 'Prison break co-op', supportsStats: false, statsApi: 'none', defaultExePath: '' },
  { id: 'lethalcompany', name: 'Lethal Company', coverImage: '/games/lethalcompany.jpg', bannerImage: '/games/lethalcompany-banner.jpg', genre: 'Horror Co-op', players: 'Co-op', rating: 8.5, description: 'Co-op horror scavenging', supportsStats: false, statsApi: 'none', defaultExePath: '' },
];

export const GAME_GENRES = Array.from(new Set(GAMES_CATALOG.map(g => g.genre)));
